(expt 2 3)
(expt 3 4)
(expt 10 0)
(expt 0 5)
(expt 1 100)
(expt -2 3)
(expt 2 10)
(define square (lambda (x) (expt x 2)))
(square 5)
(define cube (lambda (x) (expt x 3)))
(cube 4)
(define power (lambda (base exp) (expt base exp)))
(power 2 8)
(power 3 3)
(exit)
